# Generated by Django 4.0.1 on 2022-10-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_tarefeiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tarefeiros', models.ManyToManyField(to='tarefas.Tarefeiro')),
            ],
        ),
    ]
