# Generated by Django 4.0.1 on 2022-10-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_alter_tarefa_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='tarefeiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='tarefas.tarefeiro'),
        ),
    ]
