# Generated by Django 4.0.1 on 2022-10-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
